% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by NFTOOL
% Created Sat Oct 12 18:59:54 EDT 2013
%
% This script assumes these variables are defined:
%
%   X - input data.
%   T - target data.

inputs = X';
targets = T';

% Create a Fitting Network
hiddenLayerSize = 20;
net = fitnet(hiddenLayerSize);


% Setup Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 60/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 25/100;


% Train the Network
[net,tr] = train(net,inputs,targets);

% Test the Network
outputs = net(inputs);
errors = gsubtract(targets,outputs);
performance = perform(net,targets,outputs);

% View the Network
view(net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, plotfit(net,inputs,targets)
%figure, plotregression(targets,outputs)
%figure, ploterrhist(errors)
